[workspace]
resolver = "2"

members = [
    "src-rust/bincode-2-artist-wasm",
    "src-rust/artist-2-bincode-rs",
    "src-rust/shared-rs",
]

[profile.release]
lto = true
strip = true
codegen-units = 1
panic = "abort"
