name: Build and Deploy
on:
  push:
    branches: [ main ]
permissions:
    contents: write
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: oven-sh/setup-bun@v1
                with:
                    bun-version: latest
            -   uses: actions/checkout@v4
            -   name: 📦 Install dependencies
                run: bun install --frozen-lockfile
            -   name: 🛠️ Build
                run: bun run --bun generate
            -   name: 🚀 Deploy
                uses: JamesIves/github-pages-deploy-action@v4
                with:
                    branch: gh-pages
                    folder: .output/public