name: Build and Deploy
on:
  push:
    branches: [ main ]
permissions:
    contents: write
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: oven-sh/setup-bun@v1
                with:
                    bun-version: latest
            -   uses: actions/checkout@v4
            -   name: 📦 Install dependencies
                run: bun install
            -   name: 🛠️ Build
                run: bun run --bun generate
            -   name: 🚀 Deploy
                uses: peaceiris/actions-gh-pages@v4
                with:
                    deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                    external_repository: Delnegend/artist-db-dist
                    publish_dir: .output/public
    delete-old-runs:
        runs-on: ubuntu-latest
        permissions:
            actions: write
            contents: read
        steps:
            -   name: Delete workflow runs
                uses: Mattraks/delete-workflow-runs@v2
                with:
                    token: ${{ github.token }}
                    repository: ${{ github.repository }}
                    keep_minimum_runs: 0
                    retain_days: 0